# Generated by Django 5.1 on 2024-08-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student_name',
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.student'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('subject1_name', models.CharField(max_length=100)),
                ('subject1_marks', models.IntegerField()),
                ('subject2_name', models.CharField(max_length=100)),
                ('subject2_marks', models.IntegerField()),
                ('subject3_name', models.CharField(max_length=100)),
                ('subject3_marks', models.IntegerField()),
                ('subject4_name', models.CharField(max_length=100)),
                ('subject4_marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.student')),
            ],
        ),
    ]
