# Generated by Django 5.1 on 2024-08-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_semester_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
