# Generated by Django 5.1 on 2024-08-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0006_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
