# Generated by Django 5.1 on 2024-08-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_payment_paid_amount'),
        ('faculty', '0007_attendanceupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.semester'),
            preserve_default=False,
        ),
    ]
