# Generated by Django 5.1 on 2024-08-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_payment_sem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sem',
            new_name='semester',
        ),
    ]
